Microsoft/xunit-performance

- README.md
- src/xunit.performance.analysis.nuspec
- src/xunit.performance.nuspec
- src/xunit.performance.runner.Windows.nuspec
My Fork got detached from upstream (Microsoft\xunit-performance) when we made the repo public.
In the meantime, I had made a couple of trivial changes.
I just re-created the fork and now I'm merging the two changes back.
1. Add the new ```Benchmark.Iterate``` syntax to the README example.
2. Use raw.githubuser.com as the URL for LICENSE in the Nuspecs
> README and LICENSE

- src/xunit.performance.run/ProgramCore.cs
The usage text didn't line up. Since quotes have to be doubled, we need to add two extra spaces wherever they're used.
> Re-align usage text in xunit.performance.run

- src/xunit.performance.execution/BenchmarkTestInvoker.cs
This is to compensate for limited timer resolution.  This way, each iteration's measurement starts at a random distance (in time) from the previous clock tick, with the goal that any error due to clock resolution will be randomly distributed across iterations.  This should make it possible to get good data on much smaller measured regions than before.
Fixes #62.
> Insert a small random delay before each measured region

- src/xunit.performance.core/BenchmarkAttribute.cs
- src/xunit.performance.execution/BenchmarkDiscoverer.cs
This permits filtering to just benchmarks, in test assemblies that include other kinds of tests.
> Mark all Benchmarks with a trait "Benchmark=true"

- samples/SimplePerfTests/Calibration.cs
- src/xunit.performance.execution/BenchmarkConfiguration.cs
- src/xunit.performance.execution/BenchmarkTestInvoker.cs
- src/xunit.performance.run/ProgramCore.cs
- src/xunit.performance.run/xunit.performance.run.csproj
Execute for a minimum number of iterations before stopping due to any time limits.  This way longer-running tests will still produce enough data for analysis.
Fixes #91.  @ianhays
> Support for MinIterations

- src/xunit.performance.analysis/packages.config
- src/xunit.performance.analysis/xunit.performance.analysis.csproj
- src/xunit.performance.logger/packages.config
- src/xunit.performance.logger/xunit.performance.logger.csproj
- src/xunit.performance.metrics/packages.config
- src/xunit.performance.metrics/xunit.performance.metrics.csproj
- src/xunit.performance.run/packages.config
- src/xunit.performance.run/xunit.performance.run.csproj
- src/xunit.performance.runner.Windows.nuspec
This bumps the version of TraceEvent used by this framework to 1.0.39, the most recent stable version on NuGet. There were no functional changes in TraceEvent between 35 and 39, so nothing should change here other than updating the version number.
> bump TraceEvent version to 1.0.39

- samples/SimplePerfTests/StringThroughput.cs
- src/xunit.performance.core/MeasureGCAllocationsAttribute.cs
- src/xunit.performance.core/PerformanceMetricUnits.cs
- src/xunit.performance.core/xunit.performance.core.csproj
- src/xunit.performance.execution/BenchmarkTestInvoker.cs
- src/xunit.performance.metrics/GCAllocationsMetricDiscoverer.cs
- src/xunit.performance.metrics/xunit.performance.metrics.csproj
This adds a metric to track the size of allocations made on the GC heap.
Also, moves the GC trigger from being per-iteration to per-testcase.  This gives more accurate sampling of GC counts and allocations.  This may result in noisier durations, but on average they may be a more accurate representation of real performance; we'll need to gain some experience with this.
@sokket
> Add MeasureGCAllocationsAttribute

- src/xunit.performance.analysis/Program.cs
The analysis executable assumed that the name of the test duration metric was `"duration"`, with a lowercase D, which caused the MetricValues dictionary to throw since the duration metric is called `"Duration"`, with an uppercase D. This PR lifts that value into a constant and fixes all occurrences of referring to the duration metric in this dictionary with a lowercase D.
> fix name of Duration metric in the analyzer

- src/xunit.performance.metrics.nuspec
Right now, it's currently not possible to define custom metrics without adding an assembly reference to the metrics assembly, which is itself impossible when compiling with `dnu` on ASP.NET 5 since it disallows non-NuGet references entirely.
I'm in the process of validating that this works correctly at runtime, so it's not quite ready to merge, but my custom metrics compile successfully on `dnu` targeting .NET 4.6 using this package. Since the metrics assembly has a dependency on TraceEvent, so does this package, which restricts its use to .NET 4.6.
> Expose the metrics assembly as a NuGet package

- src/xunit.performance.analysis/Program.cs
Fixed a bug where the escaping logic would not take into consideration strings with multiple commas in them
@davmason @brianrob
> Fixing escaping for multiple commas in csv

- NightlyBuild.cmd
- src/cli/Microsoft.DotNet.xunit.performance.analysis.cli/project.json
- src/cli/Microsoft.DotNet.xunit.performance.runner.cli/project.json
Building executable libraries using NETStandard library since we cannot use Microsoft NetCoreApp dependencies for CoreFX
@lt72 @ericstj
> Trimming cli dependencies to NETStandard.Library

- BuildCliComponents.sh
- netci.groovy
1. Add a new script to build the CLI based components on Linux.
2. Update the CI jobs to build on Ubuntu in addition to Windows.
NOTE: This change was tested in the citest branch - it won't take effect on the CI jobs for this PR.
> Add Linux Build and CI Support

- BuildCliComponents.cmd
- CiBuild.cmd
- NightlyBuild.cmd
Prior to this change, BuildCliComponents.cmd always build Release.  Now by default it builds debug, but respects command line input to specify the build configuration.
The build configuration is also specified via NightlyBuild.cmd (which always builds release) and CiBuild.cmd (which builds both debug and release based on input).
> Plumb build configuration to BuildCliComponents.cmd

- README.md
- samples/SimplePerfTests/StringThroughput.cs
- src/cli/Microsoft.DotNet.xunit.performance.analysis.cli/project.json
- src/xunit.performance.analysis/Program.cs
- src/xunit.performance.analysis/TestStatistics.cs
- src/xunit.performance.analysis/xunit.performance.analysis.csproj
- src/xunit.performance.core/Benchmark.cs
- src/xunit.performance.core/BenchmarkAttribute.cs
- src/xunit.performance.core/BenchmarkIterator.cs
- src/xunit.performance.execution/BenchmarkConfiguration.cs
- src/xunit.performance.execution/BenchmarkEventSource.cs
- src/xunit.performance.execution/BenchmarkTestInvoker.cs
- src/xunit.performance.run/Microsoft-Xunit-Benchmark.manifest.cs
- src/xunit.performance.run/ProgramCore.cs
This change includes two stability improvements:
1. Throw out the 1st and 99th percentile results during analysis.
2. Allow for "inner iterations" to be specified.  This is to be used when a microbechmark runs too quickly and thus doesn't get measured in a stable way by the harness.  Generally, I've found that tests in the millisecond range are generating much more stable data (+ or - 1 to 3%), where as without this change, they are measuring + or - as much as 50%.
Number 2 above requires changes to test code in the form of adding an inner loop and specifying the count via [Benchmark(InnerIterationsCount=500)].  This is optional and need only be used when benchmarks execute too quickly to be accurately measured via the execution timer.
> Stability Improvements for Performance Measurements

- .gitignore
- src/cli/Microsoft.DotNet.xunit.performance.analysis.cli/project.json
- src/xunit.performance.analysis/MathExtensions.cs
- src/xunit.performance.analysis/Program.cs
- src/xunit.performance.analysis/Properties.cs
- src/xunit.performance.analysis/TestIterationResult.cs
- src/xunit.performance.analysis/TestResult.cs
- src/xunit.performance.analysis/TestResultComparison.cs
- src/xunit.performance.analysis/TestStatistics.cs
- src/xunit.performance.analysis/Writers/AbstractResultsWriter.cs
- src/xunit.performance.analysis/Writers/CsvResultsWriter.cs
- src/xunit.performance.analysis/Writers/CsvStatsWriter.cs
- src/xunit.performance.analysis/Writers/HtmlResultsWriter.cs
- src/xunit.performance.analysis/Writers/XmlResultsWriter.cs
- src/xunit.performance.analysis/xunit.performance.analysis.csproj
Refactored xunit performance analysis tool to show existing, minimal statistical analysis for all observed metrics. 
Created extensible writers for all currently used file formats.
Small addition to .gitignore
Code that writes to .csv, .xml and .http file formats has moved to the writers. The .html writer includes a small header to list all collected metrics and data points available for each metric. Observed metrics are collected at when ETW logs are parsed, and statistics are computed for all observed metrics, if data points are available.
> Apply existing comparison analysis to all observed metrics. 

- BuildCliComponents.cmd
- BuildCliComponents.sh
Installation of old cli versions is supported by scripts under the preview1 branch of dotnet cli, using this to download our cli version so our build is not broken
https://github.com/dotnet/cli/issues/3152
@lt72 @brianrob
> Fixing build breaks caused due to cli install failures

- src/xunit.performance.run.core.nuspec
Revving System.Diagnostics.Process dependencies in xunit performance since the older version indirectly references a windows-only dll and cannot be run on linux
This fixes current perf runs on linux
@brianrob @lt72
> Fixing cli runner dependencies

- NightlyBuild.cmd
- NuGet.config
- src/cli/Microsoft.DotNet.xunit.performance.runner.cli/project.json
- src/xunit.performance.nuspec
- src/xunit.performance.run.core.nuspec
This change updates the perf libraries to restore for netstandard1.3.
This involves them consuming the repackaged xunit libraries from buildtools and is dependent on PR https://github.com/dotnet/buildtools/pull/770 . I have made the Microsoft.xunit.extensibility.execution.netcore dependency versionless so that it will pick up the most recent copy(we shouldn't any updates to this package ever - this is simply a workaround until xunit ships with rc2 support).
/cc @dsgouda @brianrob @ericstj
> Update performance runners to restore for netstandard1.3

- xunit.performance.msbuild
We had a hard link on an old version of nuget that didn't work with the netstandard profile when creating nuget packages.
> Update nuget reference

- NightlyBuild.cmd
- src/xunit.performance.nuspec
- src/xunit.performance.run.core.nuspec
This is to remove the xunit dependencies preventing restore for netstandard. This will only affect the netstandard section of the nuspec.
/cc @dsgouda @brianrob
> Remove xunit dependency from nuspec for netstandard and use the new buildtools package

- NightlyBuild.cmd
- src/xunit.performance.analysis/Program.cs
- src/xunit.performance.analysis/Properties.cs
- src/xunit.performance.analysis/Writers/CsvResultsWriter.cs
- src/xunit.performance.nuspec
- src/xunit.performance.run.core.nuspec
Enabling generation of multi-metric csvs which can then be displayed on benchview.
Generating one csv file per metric as per benchview specs
fixing some dependencies in nuspec files
@lt72 
P.S.: There is some testing pending however this does generate the appropriate csv files from test results xml.
This also needs fixing of the version number
> Adding multi metric support to xunit perf analysis

- NightlyBuild.cmd
- src/xunit.performance.analysis/TestStatistics.cs
The instructions retired data was being thrown away because there were only 2 values across all iterations.  Our outlier analysis threw them out.
This change ensures that we don't throw away more than 5% of data - if we feel we need to then we don't throw any away.
@dsgouda, PTAL
> Fix InstructionsRetired Reports (Missing Data)

- README.md
In the read me references are made to `iteration.InnerIterationsCount`. This doesn't exist and at somepoint was renamed to `Benchmark.InnerIterationCount`
> Fix bug in readme

- src/common/GlobalAssemblyInfo.cs
- src/xunit.performance.analysis/xunit.performance.analysis.csproj
- src/xunit.performance.api/xunit.performance.api.csproj
- src/xunit.performance.core/xunit.performance.core.csproj
- src/xunit.performance.execution/Properties/AssemblyInfo.cs
- src/xunit.performance.execution/xunit.performance.execution.csproj
- src/xunit.performance.logger/xunit.performance.logger.csproj
- src/xunit.performance.metrics/xunit.performance.metrics.csproj
- src/xunit.performance.run/xunit.performance.run.csproj
When we made the transition to use dotnet cli to build the project we
stopped strong name signing the resulting binaries.  This caused a
problem when we try and use these binaries to build our perf tests in
the CoreFX repo.  To fix this problem we just use the
GlobablAssemblyInfo file to apply the key to all of the projects.  We
also neede to update the AssemblyInfo of the execution project because
it allows the api project to view its internal state and since the
binaries are now strong name signed we need to include the public key.
> Add back strong name signing

- src/xunit.performance.api/ETWProfiler.cs
- src/xunit.performance.api/EtwPerformanceMetricEvaluationContext.cs
- src/xunit.performance.api/Kernel32.cs
- src/xunit.performance.api/SafeTerminateHandler.cs
When the running harness was stopped with a console control signal such as: Ctrl-C, Ctrl-Break, or Close signals, the trace event session did not clean up properly, the handles to the etl files and sessions themselves persisted.
Wraps the trace event sessions in an object that subscribe them to a Ctrl listener, and dispose them accordingly when the signal is received.
Killing the process under the debugger, with the signals specified above, does not make it very happy. The process seems continue running or crashes.
> Adding a Ctrl-C, Ctrl-Break, Close handle for disposable objects.

- BuildForPublication.cmd
- src/xunit.performance.api/ETWProfiler.cs
- src/xunit.performance.api/EtwPerformanceMetricEvaluationContext.cs
- src/xunit.performance.api/PerformanceMonitorCounter/BasePerformanceMonitorCounter.cs
- src/xunit.performance.api/PerformanceMonitorCounter/BranchMispredictionsPerformanceMonitorCounter.cs
- src/xunit.performance.api/PerformanceMonitorCounter/CacheMissesPerformanceMonitorCounter.cs
- src/xunit.performance.api/PerformanceMonitorCounter/GenericPerformanceMonitorCounterDiscoverer.cs
- src/xunit.performance.api/PerformanceMonitorCounter/GenericPerformanceMonitorCounterEvaluator.cs
- src/xunit.performance.api/PerformanceMonitorCounter/GenericPerformanceMonitorCounterMetric.cs
- src/xunit.performance.api/PerformanceMonitorCounter/IPerformanceMonitorCounter.cs
- src/xunit.performance.api/XunitBenchmark.cs
- src/xunit.performance.api/XunitRunner.cs
- tests/simpleharness/Program.cs
1. Doubled the trace event session's object buffer size
2. Parse Pmc default collected data (Branch misspredictions + Cache misses)
3. Fix a bug on the xunit runner that was not filtering on Benchmark and was running all Xunit Facts.
> New metrics parsing + bug fixes

- src/xunit.performance.api/Model/AssemblyModel.cs
- src/xunit.performance.api/SafeTerminateHandler.cs
- src/xunit.performance.api/ScenarioConfiguration.cs
- src/xunit.performance.api/XunitPerformanceHarness.cs
- src/xunit.performance.api/xunit.performance.api.csproj
- src/xunit.performance.core/xunit.performance.core.csproj
- src/xunit.performance.execution/xunit.performance.execution.csproj
- src/xunit.performance.metrics/xunit.performance.metrics.csproj
- Packing xml documentation of the API to enable intellisense information to end users
(disable warning for missing documentation on public APIs)
- Fixed a bug on the ScenarioConfiguration where we were using `TimeSpam.Milliseconds` instead of `TimeSpam.TotalMilliseconds`
- Removed unused pre-package target from the xUnit Performance API csproj file
> Small fixes

- BuildForPublication.cmd
- src/xunit.performance.api/ConsoleDiagnosticMessageSink.cs
- src/xunit.performance.core/OptimizeForBenchmarksAttribute.cs
- Unable to create custom test framework discoverer type 'xunit.performance.execution.{Platform}'
> Fixing typo in attribute string

- README.md
From the discussion with @jorive, this step is not needed anymore.
cc @joshfree
> No need to reference xUnit NuGet package in README

- BuildForPublication.cmd
- src/xunit.performance.api/CSVMetricReader.cs
- src/xunit.performance.api/Model/AssemblyModel.cs
- src/xunit.performance.execution/BenchmarkEventSource.cs
Running the current `simpleharness` test project on a French system throws the following exception.
```
Unhandled Exception: System.Exception: Found unknown event:  "simpleharness.EmptyBenchmarkTest.Implementation_1", on "20170509124650.csv"
```
This PR attempts at fixing this issue.
Second commit just tweaks the xml serializer to make it generate a more XML friendly representation of a float. Would you feel this addition is unneeded, I'd be happy to drop it.
> Let's be friendly with locales using the comma "," as a decimal separator

- BuildForPublication.cmd
- NuGet.config
- src/xunit.performance.core/BenchmarkIterator.cs
- src/xunit.performance.execution/BenchmarkTestInvoker.cs
- Solving issue: https://github.com/Microsoft/xunit-performance/issues/230
> Removing virtual getter for Benchmark.InnerIterationCount.

- BuildForPublication.cmd
- src/xunit.performance.api/Model/AssemblyModel.cs
Serializing an object to Xml requires the properties to have public get/set, and the property `ScenarioTestModel.Name.set()` was private. This caused the serialized object not to have an Xml Name attribute which broke serialization to BenchView data.
> The `ScenarioTestModel` is not serializing properly to Xml.

- BuildForPublication.cmd
- build.cmd
- src/xunit.performance.api/MarkdownHelper.cs
- src/xunit.performance.api/Model/AssemblyModel.cs
- src/xunit.performance.api/Model/TableHeader.cs
- src/xunit.performance.api/ScenarioConfiguration.cs
- src/xunit.performance.api/ScenarioExecutionResult.cs
- src/xunit.performance.api/ScenarioTest.cs
- src/xunit.performance.api/ScenarioTestConfiguration.cs
- src/xunit.performance.api/XunitPerformanceHarness.cs
- tests/scenariobenchmark/Program.cs
- tests/scenariobenchmark/scenariobenchmark.csproj
- xunit-performance.sln
This makes some changes to scenario testing:
- Multiple tests can be run under a single `ScenarioBenchmark`
- Statistics output can be deferred in order to aggregate the results from multiple scenarios
- When creating tables for the results, it is possible to have a column for the scenario name
An example of code that uses the updated capabilities is here: https://github.com/dsplaisted/sdk/blob/17903b0e263aa0835d333f465972889b82670c21/test/Microsoft.NET.Perf.Tests/PerfTest.cs
It creates results like this:
Scenario Name             | Test Name          | Metric         | Unit | Iterations |    Average |  STDEV.S |        Min |        Max
:------------------------- |:------------------ |:-------------- |:----:|:----------:| ----------:| --------:| ----------:| ----------:
.NET Core 2 …
> Add more capabilities to scenario tests

- BuildForPublication.cmd
- build.cmd
- src/xunit.performance.api/FunctionalExtensions.cs
- src/xunit.performance.api/PerformanceMonitorCounter/BasePerformanceMonitorCounter.cs
- src/xunit.performance.api/Profilers/ETWProfiler.cs
- src/xunit.performance.api/Profilers/Etw/DotNetMethod.cs
- src/xunit.performance.api/Profilers/Etw/DotNetModule.cs
- src/xunit.performance.api/Profilers/Etw/KernelProvider.cs
- src/xunit.performance.api/Profilers/Etw/Listener.cs
- src/xunit.performance.api/Profilers/Etw/Module.cs
- src/xunit.performance.api/Profilers/Etw/Process.cs
- src/xunit.performance.api/Profilers/Etw/RuntimeInstance.cs
- src/xunit.performance.api/Profilers/Etw/SimpleTraceEventParser.cs
- src/xunit.performance.api/Profilers/Etw/UserProvider.cs
- src/xunit.performance.api/SafeTerminateHandler.cs
- src/xunit.performance.api/XunitBenchmark.cs
- src/xunit.performance.api/XunitPerformanceHarness.cs
- src/xunit.performance.execution/BenchmarkTestInvoker.cs
- src/xunit.performance.metrics/InstructionsRetiredMetric.cs
- tests/scenariobenchmark/Program.cs
- tests/simpleharness/simpleharness.csproj
- Remove an extra ; from the `<TargetFrameworks>` on the simpleharness.csproj file.
- xUnit micro-benchmarks harness: Call `GC.Collect` once more right after `GC.WaitForPendingFinalizers`
- Added more docstrings to public apis
- Updated the default Etw kernel/user providers, and remove duplication
- Minor changes in the xUnit Api tests verbosity
- Handle parsing `$CLRHELPERS$` methods generated by the Jit on x86
- Handle reloading unloaded modules
What is missing here?
- Implementation is complete and correct, but performance is not the best, it can be improved.
> Small series of bug fixes

- BuildForPublication.cmd
- src/xunit.performance.api/ProcessExitInfo.cs
- src/xunit.performance.api/ScenarioExecutionResult.cs
- src/xunit.performance.api/XunitPerformanceHarness.cs
- The `Process.StartTime` throw `System.ComponentModel.Win32Exception` on Linux because the data is not available once the process exits.
> System.Diagnostics.Process has a different behavior on non-Windows platforms

- BuildForPublication.cmd
- build.cmd
- dotnet-install.cmd
- src/xunit.performance.api/XunitPerformanceHarness.cs
- src/xunit.performance.api/xunit.performance.api.csproj
- src/xunit.performance.execution/AllocatedBytesForCurrentThread.cs
- src/xunit.performance.execution/xunit.performance.execution.csproj
- src/xunit.performance.metrics/xunit.performance.metrics.csproj
- tests/scenariobenchmark/Program.cs
- tests/scenariobenchmark/scenariobenchmark.csproj
- tests/simpleharness/Program.cs
- tests/simpleharness/simpleharness.csproj
- tests/standalonesample/standalonesample.csproj
Our packages were targeting netstandard1.5, but they are not working when targeting desktop. While we are investigating, I'm adding to the build matrix net461 to unblock desktop perf investigations.
> Creating new Desktop binaries to unblock Desktop support.

- BuildForPublication.cmd
- src/xunit.performance.api/Profilers/ETWProfiler.cs
- src/xunit.performance.api/XunitPerformanceHarness.cs
- src/xunit.performance.api/XunitRunner.cs
- tests/simpleharness/GetAllocatedBytesForCurrentThreadTest.cs
- tests/simpleharness/Program.cs
- After running all benchmarks now we throw an exception if a benchmark failed.
- This is mainly meant to catch bad code gen or broken benchmarks on automation.
- Add an example where a Benchmark attribute is marked to be skipped. 
- Disable the GetAllocatedBytesForCurrentThreadTest on non-netcoreapp[1.1|2.0]
- Updating some error message strings. 
- Simplified a DEBUG ONLY function.
> Minor changes and bug fixes.

- README.md
As discussed with @jorive : we advise the users to use existing uxnit feature when they want to control the order of benchmarks.
> added info about ordering benchmarks to readme, #238

- src/version.props
- src/xunit.performance.api/ConsoleDiagnosticMessageSink.cs
- src/xunit.performance.api/PerformanceTestMessageSink.cs
- src/xunit.performance.api/XunitBenchmark.cs
- src/xunit.performance.api/xunit.performance.api.csproj
- Update xUnit packages to version 2.2.0
- Update CommandLineParser package to version 2.2.1
> Update xUnit and CommandLineParser NuGet packages to stable versions

- BuildForPublication.cmd
- README.md
- src/version.props
- src/xunit.performance.api/xunit.performance.api.csproj
- src/xunit.performance.metrics/xunit.performance.metrics.csproj
- tests/standalonesample/standalonesample.csproj
Updated: This PR updates xunit-performance to use TraceEvent 2.0.5 which contains the fixes necessary to run against netstandard1.6.
------------------------------
OLD:
In order to move off of the pre-release version of TraceEvent to a shipped version (2.0.4) we need to do two this:
1. Update the nuget package reference to 2.0.4.
2. Remove support for netcoreapp1.0 and 1.1.
Older versions of the harness can still run on netcoreapp1.0 and 1.1, but the official TraceEvent package does not support versions of netcoreapp older than 2.0.  This is because there are some support DLLs that won't run on previous versions without a decent amount of work.  They work on 2.0 because enough type-forwarders have been added to mscorlib to handle the work that these DLLs do, but these type-forwarders …
> Upgrade to TraceEvent 2.0.5

- src/version.props
- src/xunit.performance.api/ConsoleDiagnosticMessageSink.cs
- src/xunit.performance.api/PerformanceTestMessageVisitor.cs
- src/xunit.performance.api/XunitBenchmark.cs
- src/xunit.performance.api/xunit.performance.api.csproj
Reverts commit 03e7799c6b8bfdb01c168f1e737adb085cb93938.
XUnit-Performance must maintain the same dependencies are CoreFX in order to ensure that there are not conflicts.  CoreFX is unique as it does not support ProjectReferences (and thus specifying unique references per component).
> Downgrade XUnit-Performance Dependencies

- src/xunit.performance.api/xunit.performance.api.csproj
- src/xunit.performance.execution/xunit.performance.execution.csproj
@jorive this fixes the test error and also replaces the alpha dependency with a stable netstandard2.0 package. This removes a compiler warnings because of two different assembly identities. I also opened a PR but I doubt it will be accepted as the project seems dead: https://github.com/Wheelies/MarkdownLog/pull/16
You can now publish the packages. Thanks!
> Remove unstable package & cross compile executor
